/**
 * Static meal template catalog — the source of truth for generated plans.
 *
 * Each Meal includes macros, diet compatibility, allergy exclusions, and
 * optional cooking steps. mealGenerator filters this list by profile, then
 * picks meals per slot. Templates are hand-authored (not API-generated).
 */
import type { Allergy, DietType, Meal, MealSlot } from '@/types';

/** Full library of breakfast, lunch, dinner, and snack templates. */
export const MEAL_TEMPLATES: Meal[] = [
  {
    id: 'b1',
    name: 'Greek Yogurt & Berries',
    slot: 'breakfast',
    ingredients: ['Greek yogurt', 'mixed berries', 'honey'],
    macros: { calories: 320, protein: 22, carbs: 38, fat: 8 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean'],
    excludesAllergies: ['gluten', 'nuts'],
  },
  {
    id: 'b2',
    name: 'Oatmeal with Banana',
    slot: 'breakfast',
    ingredients: ['oats', 'banana', 'almond milk'],
    macros: { calories: 380, protein: 12, carbs: 68, fat: 7 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['dairy', 'eggs', 'gluten'],
  },
  {
    id: 'b3',
    name: 'Scrambled Eggs & Toast',
    slot: 'breakfast',
    ingredients: ['eggs', 'whole wheat bread', 'spinach'],
    macros: { calories: 420, protein: 28, carbs: 32, fat: 18 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['dairy', 'nuts'],
  },
  {
    id: 'b4',
    name: 'Keto Avocado Eggs',
    slot: 'breakfast',
    ingredients: ['eggs', 'avocado', 'olive oil'],
    macros: { calories: 450, protein: 24, carbs: 6, fat: 38 },
    dietTypes: ['omnivore', 'keto'],
    excludesAllergies: ['gluten', 'dairy', 'nuts'],
  },
  {
    id: 'b5',
    name: 'Avocado Toast',
    slot: 'breakfast',
    ingredients: ['sourdough bread', 'avocado', 'lemon juice', 'chili flakes', 'olive oil'],
    macros: { calories: 390, protein: 10, carbs: 42, fat: 22 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['nuts', 'dairy', 'eggs'],
    cookingSteps: [
      'Toast the sourdough bread until golden and crispy.',
      'Halve the avocado, remove the pit, and scoop the flesh into a bowl.',
      'Mash the avocado with lemon juice, salt, and pepper.',
      'Spread the mashed avocado generously over the toast.',
      'Drizzle with olive oil and sprinkle chili flakes on top.',
    ],
    cookTime: 10,
    difficulty: 'Easy',
  },
  {
    id: 'b6',
    name: 'Protein Pancakes',
    slot: 'breakfast',
    ingredients: ['oats', 'banana', 'eggs', 'protein powder', 'cinnamon'],
    macros: { calories: 440, protein: 34, carbs: 48, fat: 10 },
    dietTypes: ['omnivore'],
    excludesAllergies: ['gluten', 'dairy', 'nuts'],
    cookingSteps: [
      'Blend oats, banana, eggs, protein powder, and cinnamon until smooth.',
      'Heat a non-stick pan over medium heat and lightly grease it.',
      'Pour small rounds of batter onto the pan.',
      'Cook for 2-3 minutes until bubbles form, then flip.',
      'Cook another 1-2 minutes until golden. Serve warm.',
    ],
    cookTime: 15,
    difficulty: 'Easy',
  },
  {
    id: 'b7',
    name: 'Greek Omelette',
    slot: 'breakfast',
    ingredients: ['eggs', 'feta cheese', 'spinach', 'tomatoes', 'olive oil'],
    macros: { calories: 380, protein: 26, carbs: 8, fat: 28 },
    dietTypes: ['omnivore', 'vegetarian', 'keto', 'mediterranean'],
    excludesAllergies: ['gluten', 'nuts'],
    cookingSteps: [
      'Whisk 3 eggs with salt and pepper in a bowl.',
      'Heat olive oil in a pan over medium heat.',
      'Add spinach and tomatoes, sauté for 2 minutes.',
      'Pour in the eggs and let them set for 1 minute.',
      'Add crumbled feta, fold the omelette in half, and serve.',
    ],
    cookTime: 10,
    difficulty: 'Easy',
  },
  {
    id: 'b8',
    name: 'Chia Pudding',
    slot: 'breakfast',
    ingredients: ['chia seeds', 'almond milk', 'honey', 'mixed berries', 'vanilla extract'],
    macros: { calories: 310, protein: 10, carbs: 36, fat: 14 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'eggs', 'nuts'],
    cookingSteps: [
      'Mix chia seeds with almond milk and vanilla extract in a jar.',
      'Stir well to prevent clumping.',
      'Add honey and stir again.',
      'Refrigerate overnight or for at least 4 hours.',
      'Top with fresh mixed berries before serving.',
    ],
    cookTime: 5,
    difficulty: 'Easy',
  },
  {
    id: 'l1',
    name: 'Grilled Chicken Salad',
    slot: 'lunch',
    ingredients: ['chicken breast', 'lettuce', 'tomato', 'olive oil'],
    macros: { calories: 480, protein: 42, carbs: 18, fat: 26 },
    dietTypes: ['omnivore', 'keto', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'nuts', 'eggs'],
  },
  {
    id: 'l2',
    name: 'Lentil Soup & Bread',
    slot: 'lunch',
    ingredients: ['lentils', 'carrots', 'celery', 'bread'],
    macros: { calories: 520, protein: 22, carbs: 78, fat: 10 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['dairy', 'nuts', 'eggs'],
  },
  {
    id: 'l3',
    name: 'Tofu Buddha Bowl',
    slot: 'lunch',
    ingredients: ['tofu', 'brown rice', 'broccoli', 'sesame'],
    macros: { calories: 540, protein: 28, carbs: 62, fat: 18 },
    dietTypes: ['vegetarian', 'vegan'],
    excludesAllergies: ['dairy', 'eggs', 'gluten'],
  },
  {
    id: 'l4',
    name: 'Salmon & Quinoa',
    slot: 'lunch',
    ingredients: ['salmon', 'quinoa', 'asparagus'],
    macros: { calories: 580, protein: 38, carbs: 42, fat: 28 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'nuts', 'eggs'],
  },
  {
    id: 'l5',
    name: 'Tuna Niçoise Salad',
    slot: 'lunch',
    ingredients: ['tuna', 'green beans', 'boiled eggs', 'olives', 'cherry tomatoes', 'olive oil'],
    macros: { calories: 460, protein: 38, carbs: 20, fat: 24 },
    dietTypes: ['omnivore', 'mediterranean', 'keto'],
    excludesAllergies: ['gluten', 'dairy', 'nuts'],
    cookingSteps: [
      'Boil green beans for 3 minutes then cool in ice water.',
      'Hard boil eggs for 8 minutes, peel and halve.',
      'Drain tuna and flake into a bowl.',
      'Arrange all ingredients on a plate.',
      'Drizzle with olive oil and season with salt and pepper.',
    ],
    cookTime: 20,
    difficulty: 'Easy',
  },
  {
    id: 'l6',
    name: 'Chicken Souvlaki Bowl',
    slot: 'lunch',
    ingredients: ['chicken breast', 'pita bread', 'tzatziki', 'tomatoes', 'red onion', 'olive oil'],
    macros: { calories: 560, protein: 44, carbs: 46, fat: 18 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['nuts', 'eggs'],
    cookingSteps: [
      'Cut chicken into cubes and marinate with olive oil, lemon, oregano for 30 minutes.',
      'Thread onto skewers and grill on high heat for 10-12 minutes, turning occasionally.',
      'Warm the pita bread on the grill for 1 minute each side.',
      'Slice tomatoes and red onion thinly.',
      'Assemble bowl with pita, chicken, vegetables, and a generous dollop of tzatziki.',
    ],
    cookTime: 45,
    difficulty: 'Medium',
  },
  {
    id: 'l7',
    name: 'Falafel Wrap',
    slot: 'lunch',
    ingredients: ['chickpeas', 'pita bread', 'tahini', 'cucumber', 'tomatoes', 'parsley'],
    macros: { calories: 500, protein: 18, carbs: 66, fat: 18 },
    dietTypes: ['vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['dairy', 'eggs', 'nuts'],
    cookingSteps: [
      'Blend chickpeas with parsley, garlic, cumin, and salt into a rough paste.',
      'Form into small patties and pan-fry in olive oil for 3-4 minutes each side.',
      'Warm pita bread and spread tahini sauce.',
      'Add sliced cucumber and tomatoes.',
      'Place falafel inside, wrap tightly, and serve.',
    ],
    cookTime: 25,
    difficulty: 'Medium',
  },
  {
    id: 'l8',
    name: 'Quinoa Tabbouleh',
    slot: 'lunch',
    ingredients: ['quinoa', 'parsley', 'mint', 'tomatoes', 'cucumber', 'lemon juice', 'olive oil'],
    macros: { calories: 420, protein: 14, carbs: 58, fat: 16 },
    dietTypes: ['vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'eggs', 'nuts'],
    cookingSteps: [
      'Cook quinoa according to package instructions and let cool completely.',
      'Finely chop parsley, mint, tomatoes, and cucumber.',
      'Mix all vegetables with cooled quinoa in a large bowl.',
      'Dress with lemon juice, olive oil, salt, and pepper.',
      'Toss well and refrigerate for 30 minutes before serving.',
    ],
    cookTime: 40,
    difficulty: 'Easy',
  },
  {
    id: 'd1',
    name: 'Turkey Stir-Fry',
    slot: 'dinner',
    ingredients: ['turkey', 'peppers', 'rice noodles'],
    macros: { calories: 520, protein: 36, carbs: 58, fat: 14 },
    dietTypes: ['omnivore'],
    excludesAllergies: ['dairy', 'nuts', 'eggs'],
  },
  {
    id: 'd2',
    name: 'Mediterranean Chickpea Bowl',
    slot: 'dinner',
    ingredients: ['chickpeas', 'cucumber', 'feta', 'olive oil'],
    macros: { calories: 490, protein: 18, carbs: 52, fat: 22 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean'],
    excludesAllergies: ['gluten', 'nuts', 'eggs'],
  },
  {
    id: 'd3',
    name: 'Zucchini Noodles & Pesto',
    slot: 'dinner',
    ingredients: ['zucchini', 'basil pesto', 'cherry tomatoes'],
    macros: { calories: 380, protein: 12, carbs: 24, fat: 28 },
    dietTypes: ['vegetarian', 'keto', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'eggs'],
  },
  {
    id: 'd4',
    name: 'Beef & Sweet Potato',
    slot: 'dinner',
    ingredients: ['lean beef', 'sweet potato', 'green beans'],
    macros: { calories: 620, protein: 44, carbs: 48, fat: 26 },
    dietTypes: ['omnivore', 'keto'],
    excludesAllergies: ['gluten', 'dairy', 'nuts', 'eggs'],
  },
  {
    id: 'd5',
    name: 'Baked Salmon with Vegetables',
    slot: 'dinner',
    ingredients: ['salmon fillet', 'broccoli', 'cherry tomatoes', 'olive oil', 'lemon', 'garlic'],
    macros: { calories: 520, protein: 42, carbs: 18, fat: 32 },
    dietTypes: ['omnivore', 'mediterranean', 'keto'],
    excludesAllergies: ['gluten', 'dairy', 'nuts', 'eggs'],
    cookingSteps: [
      'Preheat oven to 200°C.',
      'Place salmon on a baking tray, season with salt, pepper, and minced garlic.',
      'Arrange broccoli and cherry tomatoes around the salmon.',
      'Drizzle everything with olive oil and lemon juice.',
      'Bake for 18-20 minutes until salmon flakes easily with a fork.',
    ],
    cookTime: 30,
    difficulty: 'Easy',
  },
  {
    id: 'd6',
    name: 'Moussaka',
    slot: 'dinner',
    ingredients: ['minced beef', 'eggplant', 'tomatoes', 'onion', 'cinnamon', 'olive oil', 'milk', 'flour'],
    macros: { calories: 580, protein: 32, carbs: 38, fat: 32 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['nuts', 'eggs'],
    cookingSteps: [
      'Slice eggplant, salt it, and let sit for 20 minutes. Pat dry and grill until soft.',
      'Brown minced beef with onion, add crushed tomatoes, cinnamon, salt, and pepper. Simmer 15 minutes.',
      'Make a simple béchamel: melt butter, whisk in flour, gradually add warm milk, stir until thick.',
      'Layer eggplant, meat sauce, and béchamel in a baking dish.',
      'Bake at 180°C for 40 minutes until golden on top. Rest 10 minutes before serving.',
    ],
    cookTime: 90,
    difficulty: 'Hard',
  },
  {
    id: 'd7',
    name: 'Shrimp Pasta',
    slot: 'dinner',
    ingredients: ['shrimp', 'pasta', 'garlic', 'cherry tomatoes', 'olive oil', 'parsley', 'lemon'],
    macros: { calories: 540, protein: 36, carbs: 58, fat: 16 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'nuts', 'eggs'],
    cookingSteps: [
      'Cook pasta in salted boiling water until al dente. Reserve half a cup of pasta water.',
      'Sauté minced garlic in olive oil for 1 minute until fragrant.',
      'Add shrimp and cook 2 minutes per side until pink.',
      'Add cherry tomatoes and cook 3 more minutes.',
      'Toss in drained pasta with a splash of pasta water. Finish with parsley and lemon juice.',
    ],
    cookTime: 25,
    difficulty: 'Easy',
  },
  {
    id: 'd8',
    name: 'Stuffed Peppers',
    slot: 'dinner',
    ingredients: ['bell peppers', 'brown rice', 'minced turkey', 'tomatoes', 'onion', 'feta cheese'],
    macros: { calories: 490, protein: 34, carbs: 46, fat: 18 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['gluten', 'nuts', 'eggs'],
    cookingSteps: [
      'Cook brown rice until tender. Preheat oven to 180°C.',
      'Brown turkey mince with onion and crushed tomatoes. Season well.',
      'Mix turkey with cooked rice and crumbled feta.',
      'Cut tops off peppers, remove seeds, and fill with the mixture.',
      'Place in a baking dish with a little water, cover with foil, bake 35 minutes.',
    ],
    cookTime: 60,
    difficulty: 'Medium',
  },
  {
    id: 's1',
    name: 'Apple & Almond Butter',
    slot: 'snack',
    ingredients: ['apple', 'almond butter'],
    macros: { calories: 220, protein: 6, carbs: 28, fat: 12 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'eggs'],
  },
  {
    id: 's2',
    name: 'Protein Shake',
    slot: 'snack',
    ingredients: ['whey protein', 'banana', 'milk'],
    macros: { calories: 280, protein: 32, carbs: 30, fat: 4 },
    dietTypes: ['omnivore'],
    excludesAllergies: ['gluten', 'nuts', 'eggs'],
  },
  {
    id: 's3',
    name: 'Hummus & Carrots',
    slot: 'snack',
    ingredients: ['hummus', 'carrot sticks'],
    macros: { calories: 180, protein: 6, carbs: 22, fat: 8 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean', 'keto'],
    excludesAllergies: ['gluten', 'dairy', 'eggs', 'nuts'],
  },
  {
    id: 's4',
    name: 'Cheese & Crackers',
    slot: 'snack',
    ingredients: ['cheddar', 'crackers'],
    macros: { calories: 240, protein: 10, carbs: 18, fat: 14 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean'],
    excludesAllergies: ['nuts', 'eggs', 'gluten'],
  },
  {
    id: 's5',
    name: 'Greek Yogurt with Honey',
    slot: 'snack',
    ingredients: ['Greek yogurt', 'honey', 'walnuts', 'cinnamon'],
    macros: { calories: 200, protein: 14, carbs: 22, fat: 8 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean'],
    excludesAllergies: ['gluten', 'eggs'],
    cookingSteps: [
      'Spoon Greek yogurt into a bowl.',
      'Drizzle honey over the top.',
      'Sprinkle crushed walnuts and a pinch of cinnamon.',
      'Serve immediately.',
    ],
    cookTime: 3,
    difficulty: 'Easy',
  },
  {
    id: 's6',
    name: 'Rice Cakes with Peanut Butter',
    slot: 'snack',
    ingredients: ['rice cakes', 'peanut butter', 'banana', 'chia seeds'],
    macros: { calories: 250, protein: 8, carbs: 34, fat: 10 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan'],
    excludesAllergies: ['gluten', 'dairy', 'eggs'],
    cookingSteps: [
      'Place rice cakes on a plate.',
      'Spread peanut butter evenly over each rice cake.',
      'Slice banana and arrange on top.',
      'Sprinkle chia seeds over everything.',
    ],
    cookTime: 3,
    difficulty: 'Easy',
  },
  {
    id: 's7',
    name: 'Mixed Nuts & Dried Fruit',
    slot: 'snack',
    ingredients: ['almonds', 'walnuts', 'dried cranberries', 'dark chocolate chips'],
    macros: { calories: 260, protein: 7, carbs: 24, fat: 16 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'eggs'],
    cookingSteps: [
      'Measure out portions of almonds, walnuts, cranberries, and chocolate chips.',
      'Mix together in a small bowl.',
      'Serve immediately or store in an airtight container.',
    ],
    cookTime: 2,
    difficulty: 'Easy',
  },
  {
    id: 'b9',
    name: 'Smoked Salmon Bagel',
    slot: 'breakfast',
    ingredients: ['bagel', 'smoked salmon', 'cream cheese', 'cucumber', 'dill', 'capers'],
    macros: { calories: 450, protein: 28, carbs: 42, fat: 18 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['nuts', 'eggs'],
    cookingSteps: [
      'Slice the bagel in half and toast both cut sides until golden and crisp, about 2 minutes.',
      'Spread a generous layer of cream cheese evenly over each toasted half.',
      'Layer thin slices of smoked salmon over the cream cheese, folding gently for volume.',
      'Slice cucumber into thin rounds and arrange on top of the salmon.',
      'Scatter capers and fresh dill over the bagel halves.',
      'Season lightly with black pepper and serve immediately while the bagel is still warm.',
    ],
    cookTime: 8,
    difficulty: 'Easy',
  },
  {
    id: 'b10',
    name: 'Cottage Cheese Bowl',
    slot: 'breakfast',
    ingredients: ['cottage cheese', 'granola', 'blueberries', 'honey', 'almonds'],
    macros: { calories: 340, protein: 30, carbs: 28, fat: 12 },
    dietTypes: ['omnivore', 'vegetarian'],
    excludesAllergies: ['dairy', 'nuts', 'eggs'],
    cookingSteps: [
      'Spoon cottage cheese into a wide bowl, spreading it evenly to create a flat base.',
      'Wash and pat dry the blueberries, then scatter them over the cottage cheese.',
      'Sprinkle granola over the berries in an even layer for crunch.',
      'Roughly chop the almonds and distribute them across the bowl.',
      'Drizzle honey over the top in a thin stream.',
      'Serve immediately so the granola stays crisp.',
    ],
    cookTime: 5,
    difficulty: 'Easy',
  },
  {
    id: 'b11',
    name: 'Vegan Tofu Scramble',
    slot: 'breakfast',
    ingredients: ['firm tofu', 'turmeric', 'spinach', 'cherry tomatoes', 'nutritional yeast', 'olive oil'],
    macros: { calories: 360, protein: 22, carbs: 18, fat: 22 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan'],
    excludesAllergies: ['eggs'],
    cookingSteps: [
      'Press the firm tofu for 5 minutes, then crumble it into small pieces with your hands.',
      'Heat olive oil in a non-stick pan over medium heat for 1 minute until shimmering.',
      'Add crumbled tofu, turmeric, salt, and pepper; sauté for 4 minutes, stirring frequently.',
      'Halve the cherry tomatoes and add them along with the spinach to the pan.',
      'Cook for 3 more minutes until the spinach wilts and tomatoes soften slightly.',
      'Remove from heat, sprinkle nutritional yeast over the scramble, and toss to combine.',
      'Taste and adjust seasoning before serving warm.',
    ],
    cookTime: 12,
    difficulty: 'Easy',
  },
  {
    id: 'b12',
    name: 'Banana Walnut Oatmeal',
    slot: 'breakfast',
    ingredients: ['oats', 'banana', 'walnuts', 'cinnamon', 'milk', 'honey'],
    macros: { calories: 420, protein: 14, carbs: 62, fat: 14 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean'],
    excludesAllergies: ['dairy', 'nuts', 'eggs'],
    cookingSteps: [
      'Bring milk to a gentle simmer in a small saucepan over medium heat, about 2 minutes.',
      'Stir in oats and a pinch of cinnamon; reduce heat to low and cook for 5 minutes, stirring often.',
      'Slice half the banana and mash the other half, then stir the mashed banana into the oatmeal.',
      'Roughly chop the walnuts and fold them into the cooked oats.',
      'Transfer to a bowl, top with banana slices and a drizzle of honey.',
      'Sprinkle with an extra pinch of cinnamon and serve hot.',
    ],
    cookTime: 10,
    difficulty: 'Easy',
  },
  {
    id: 'b13',
    name: 'Egg White Veggie Omelette',
    slot: 'breakfast',
    ingredients: ['egg whites', 'mushrooms', 'bell peppers', 'onion', 'feta', 'olive oil'],
    macros: { calories: 290, protein: 32, carbs: 8, fat: 12 },
    dietTypes: ['omnivore', 'vegetarian', 'keto', 'mediterranean'],
    excludesAllergies: ['dairy', 'eggs'],
    cookingSteps: [
      'Dice mushrooms, bell peppers, and onion into small, even pieces.',
      'Heat olive oil in a non-stick pan over medium heat for 1 minute.',
      'Sauté the vegetables for 4 minutes until softened and lightly golden.',
      'Whisk egg whites with a pinch of salt and pepper in a bowl until frothy.',
      'Pour egg whites over the vegetables and let set for 2 minutes without stirring.',
      'Crumble feta over one half, fold the omelette, and cook 1 more minute.',
      'Slide onto a plate and serve immediately.',
    ],
    cookTime: 12,
    difficulty: 'Easy',
  },
  {
    id: 'b14',
    name: 'Smoothie Bowl',
    slot: 'breakfast',
    ingredients: ['frozen berries', 'banana', 'protein powder', 'almond milk', 'chia seeds', 'granola'],
    macros: { calories: 380, protein: 18, carbs: 58, fat: 8 },
    dietTypes: ['omnivore', 'vegetarian'],
    excludesAllergies: ['gluten', 'nuts'],
    cookingSteps: [
      'Add frozen berries, banana, protein powder, and almond milk to a blender.',
      'Blend on high for 45 seconds until thick and smooth, adding more milk if needed.',
      'Pour the mixture into a chilled bowl—it should be thicker than a drinkable smoothie.',
      'Sprinkle chia seeds evenly over the surface of the bowl.',
      'Top with a handful of granola and a few extra berries for garnish.',
      'Serve immediately with a spoon before it melts.',
    ],
    cookTime: 7,
    difficulty: 'Easy',
  },
  {
    id: 'b15',
    name: 'Breakfast Burrito',
    slot: 'breakfast',
    ingredients: ['eggs', 'black beans', 'tortilla', 'cheddar', 'avocado', 'salsa'],
    macros: { calories: 510, protein: 28, carbs: 44, fat: 22 },
    dietTypes: ['omnivore', 'vegetarian'],
    excludesAllergies: ['gluten', 'dairy', 'eggs'],
    cookingSteps: [
      'Warm black beans in a small pan over medium heat for 3 minutes, mashing lightly with a fork.',
      'Scramble eggs in a separate pan over medium-low heat for 4 minutes until just set.',
      'Warm the tortilla in a dry pan for 30 seconds per side until pliable.',
      'Layer scrambled eggs, beans, and shredded cheddar down the center of the tortilla.',
      'Add sliced avocado and a spoonful of salsa on top of the filling.',
      'Fold the sides in and roll tightly into a burrito; cut in half and serve.',
    ],
    cookTime: 15,
    difficulty: 'Easy',
  },
  {
    id: 'b16',
    name: 'Ricotta Pancakes',
    slot: 'breakfast',
    ingredients: ['ricotta', 'eggs', 'flour', 'milk', 'vanilla', 'maple syrup'],
    macros: { calories: 460, protein: 22, carbs: 48, fat: 18 },
    dietTypes: ['omnivore', 'vegetarian'],
    excludesAllergies: ['gluten', 'dairy', 'eggs'],
    cookingSteps: [
      'Whisk ricotta, eggs, milk, and vanilla extract in a bowl until smooth.',
      'Sift flour into the wet mixture and fold gently until just combined—do not overmix.',
      'Heat a lightly greased non-stick pan over medium-low heat for 2 minutes.',
      'Pour ¼ cup batter per pancake; cook 3 minutes until bubbles form on the surface.',
      'Flip carefully and cook another 2 minutes until golden brown on both sides.',
      'Stack pancakes on a plate and drizzle with maple syrup before serving.',
    ],
    cookTime: 18,
    difficulty: 'Medium',
  },
  {
    id: 'l9',
    name: 'Chicken Caesar Salad',
    slot: 'lunch',
    ingredients: ['chicken breast', 'romaine', 'parmesan', 'croutons', 'caesar dressing'],
    macros: { calories: 470, protein: 40, carbs: 12, fat: 28 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'eggs'],
    cookingSteps: [
      'Season chicken breast with salt and pepper on both sides.',
      'Heat a grill pan over medium-high heat for 2 minutes and cook chicken 6 minutes per side until done.',
      'Rest the chicken for 3 minutes, then slice into thin strips.',
      'Wash and chop romaine lettuce into bite-sized pieces; place in a large bowl.',
      'Toss lettuce with Caesar dressing until evenly coated.',
      'Top with sliced chicken, shaved parmesan, and croutons; serve immediately.',
    ],
    cookTime: 20,
    difficulty: 'Easy',
  },
  {
    id: 'l10',
    name: 'Beef Burrito Bowl',
    slot: 'lunch',
    ingredients: ['lean beef', 'brown rice', 'black beans', 'corn', 'salsa', 'avocado'],
    macros: { calories: 580, protein: 38, carbs: 56, fat: 22 },
    dietTypes: ['omnivore'],
    excludesAllergies: [],
    cookingSteps: [
      'Cook brown rice according to package instructions, about 25 minutes, then fluff with a fork.',
      'Season lean beef with salt, pepper, and cumin; brown in a hot pan over medium-high heat for 6 minutes.',
      'Warm black beans and corn in a small saucepan over low heat for 3 minutes.',
      'Dice avocado and prepare salsa in separate bowls for topping.',
      'Divide rice among bowls as the base layer.',
      'Top with seasoned beef, beans, corn, salsa, and avocado; serve warm.',
    ],
    cookTime: 25,
    difficulty: 'Easy',
  },
  {
    id: 'l11',
    name: 'Mediterranean Pasta',
    slot: 'lunch',
    ingredients: ['pasta', 'cherry tomatoes', 'olives', 'feta', 'basil', 'olive oil'],
    macros: { calories: 520, protein: 18, carbs: 68, fat: 18 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'eggs'],
    cookingSteps: [
      'Bring a large pot of salted water to a boil and cook pasta until al dente, about 10 minutes.',
      'Halve cherry tomatoes and slice olives while the pasta cooks.',
      'Heat olive oil in a wide pan over medium heat for 1 minute.',
      'Add tomatoes and olives; sauté for 4 minutes until tomatoes soften slightly.',
      'Drain pasta, reserving ¼ cup pasta water, and add pasta to the pan.',
      'Toss with crumbled feta, torn basil, and a splash of pasta water; serve warm.',
    ],
    cookTime: 15,
    difficulty: 'Easy',
  },
  {
    id: 'l12',
    name: 'Sushi Bowl',
    slot: 'lunch',
    ingredients: ['sushi rice', 'smoked salmon', 'edamame', 'avocado', 'nori', 'sesame seeds'],
    macros: { calories: 490, protein: 32, carbs: 58, fat: 12 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['nuts'],
    cookingSteps: [
      'Rinse sushi rice until water runs clear, then cook according to package instructions and let cool slightly.',
      'Season warm rice with rice vinegar and a pinch of salt; fluff gently with a fork.',
      'Cook edamame in boiling salted water for 4 minutes, then drain and shell.',
      'Slice avocado and smoked salmon into thin strips; cut nori into thin ribbons.',
      'Divide rice among bowls and arrange salmon, edamame, and avocado on top.',
      'Sprinkle with sesame seeds and nori strips; serve at room temperature.',
    ],
    cookTime: 20,
    difficulty: 'Medium',
  },
  {
    id: 'l13',
    name: 'Greek Salad with Chicken',
    slot: 'lunch',
    ingredients: ['chicken', 'tomatoes', 'cucumber', 'olives', 'feta', 'red onion', 'olive oil'],
    macros: { calories: 460, protein: 36, carbs: 16, fat: 26 },
    dietTypes: ['omnivore', 'mediterranean', 'keto'],
    excludesAllergies: ['dairy'],
    cookingSteps: [
      'Season chicken with oregano, salt, and pepper; grill over medium-high heat for 6 minutes per side.',
      'Rest chicken for 3 minutes, then slice into strips.',
      'Chop tomatoes and cucumber into chunks; thinly slice red onion.',
      'Combine vegetables and olives in a large bowl.',
      'Drizzle with olive oil and toss with crumbled feta.',
      'Top with sliced chicken and serve immediately.',
    ],
    cookTime: 15,
    difficulty: 'Easy',
  },
  {
    id: 'l14',
    name: 'Tuna Pasta Salad',
    slot: 'lunch',
    ingredients: ['pasta', 'tuna', 'sweet corn', 'peas', 'mayo', 'lemon'],
    macros: { calories: 510, protein: 32, carbs: 58, fat: 14 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['gluten', 'eggs'],
    cookingSteps: [
      'Cook pasta in salted boiling water until al dente, about 10 minutes; drain and rinse under cold water.',
      'Drain canned tuna and flake into large pieces with a fork.',
      'Blanch peas in boiling water for 2 minutes, then drain and cool.',
      'Combine pasta, tuna, sweet corn, and peas in a large mixing bowl.',
      'Stir in mayonnaise and a squeeze of fresh lemon juice until evenly coated.',
      'Season with salt and pepper, chill for 10 minutes, and serve cold.',
    ],
    cookTime: 15,
    difficulty: 'Easy',
  },
  {
    id: 'l15',
    name: 'Roasted Veggie Wrap',
    slot: 'lunch',
    ingredients: ['whole wheat wrap', 'hummus', 'zucchini', 'eggplant', 'peppers', 'spinach'],
    macros: { calories: 440, protein: 14, carbs: 58, fat: 18 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['gluten'],
    cookingSteps: [
      'Preheat oven to 200°C and line a baking tray with parchment paper.',
      'Slice zucchini, eggplant, and peppers into thin strips; toss with olive oil, salt, and pepper.',
      'Roast vegetables for 18 minutes, turning once, until tender and lightly charred.',
      'Warm the whole wheat wrap in a dry pan for 30 seconds per side.',
      'Spread a thick layer of hummus across the center of the wrap.',
      'Layer roasted vegetables and fresh spinach, then roll tightly and slice in half.',
    ],
    cookTime: 20,
    difficulty: 'Easy',
  },
  {
    id: 'l16',
    name: 'Buddha Bowl Variation',
    slot: 'lunch',
    ingredients: ['quinoa', 'sweet potato', 'chickpeas', 'kale', 'tahini', 'pumpkin seeds'],
    macros: { calories: 530, protein: 22, carbs: 68, fat: 18 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['nuts'],
    cookingSteps: [
      'Cook quinoa according to package instructions, about 15 minutes; fluff and set aside.',
      'Peel and cube sweet potato; roast at 200°C for 22 minutes until tender and golden.',
      'Drain and rinse chickpeas; roast alongside sweet potato for the last 12 minutes until crisp.',
      'Massage chopped kale with a drizzle of olive oil and a pinch of salt for 2 minutes.',
      'Whisk tahini with lemon juice and water until smooth to make a dressing.',
      'Assemble bowls with quinoa, sweet potato, chickpeas, and kale; drizzle with tahini and sprinkle pumpkin seeds.',
    ],
    cookTime: 30,
    difficulty: 'Medium',
  },
  {
    id: 'l17',
    name: 'Pesto Chicken Pasta',
    slot: 'lunch',
    ingredients: ['pasta', 'chicken breast', 'basil pesto', 'cherry tomatoes', 'parmesan'],
    macros: { calories: 580, protein: 42, carbs: 56, fat: 18 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy'],
    cookingSteps: [
      'Cook pasta in salted boiling water until al dente, about 10 minutes; reserve ¼ cup pasta water.',
      'Season chicken breast and pan-sear over medium-high heat for 6 minutes per side until cooked through.',
      'Rest chicken for 3 minutes, then slice into bite-sized pieces.',
      'Halve cherry tomatoes and warm them in the same pan for 2 minutes.',
      'Toss drained pasta with basil pesto and a splash of reserved pasta water.',
      'Add sliced chicken and tomatoes, top with shaved parmesan, and serve immediately.',
    ],
    cookTime: 20,
    difficulty: 'Easy',
  },
  {
    id: 'd9',
    name: 'Chicken Curry',
    slot: 'dinner',
    ingredients: ['chicken thigh', 'coconut milk', 'curry paste', 'basmati rice', 'onion', 'ginger'],
    macros: { calories: 540, protein: 40, carbs: 42, fat: 22 },
    dietTypes: ['omnivore'],
    excludesAllergies: [],
    cookingSteps: [
      'Cook basmati rice according to package instructions and keep warm.',
      'Dice onion and mince ginger; cut chicken thighs into bite-sized pieces.',
      'Heat oil in a large pan over medium heat and sauté onion and ginger for 3 minutes.',
      'Stir in curry paste and cook for 1 minute until fragrant.',
      'Add chicken pieces and brown for 5 minutes on all sides.',
      'Pour in coconut milk, bring to a simmer, and cook uncovered for 20 minutes until chicken is tender.',
      'Serve curry over basmati rice.',
    ],
    cookTime: 35,
    difficulty: 'Medium',
  },
  {
    id: 'd10',
    name: 'Spaghetti Bolognese',
    slot: 'dinner',
    ingredients: ['spaghetti', 'minced beef', 'tomato sauce', 'onion', 'garlic', 'parmesan'],
    macros: { calories: 620, protein: 38, carbs: 72, fat: 18 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy'],
    cookingSteps: [
      'Cook spaghetti in salted boiling water until al dente, about 10 minutes; drain and set aside.',
      'Finely dice onion and mince garlic; sauté in olive oil over medium heat for 4 minutes.',
      'Add minced beef and cook for 6 minutes, breaking it up with a spoon until browned.',
      'Pour in tomato sauce, season with salt and pepper, and simmer for 15 minutes.',
      'Toss spaghetti with the bolognese sauce until well coated.',
      'Serve in bowls topped with freshly grated parmesan.',
    ],
    cookTime: 30,
    difficulty: 'Easy',
  },
  {
    id: 'd11',
    name: 'Beef Stir-Fry',
    slot: 'dinner',
    ingredients: ['lean beef strips', 'broccoli', 'bell peppers', 'soy sauce', 'ginger', 'rice'],
    macros: { calories: 510, protein: 38, carbs: 42, fat: 18 },
    dietTypes: ['omnivore'],
    excludesAllergies: [],
    cookingSteps: [
      'Cook rice according to package instructions and keep warm.',
      'Slice bell peppers and cut broccoli into small florets.',
      'Heat a wok or large pan over high heat for 2 minutes until very hot.',
      'Stir-fry beef strips for 3 minutes until browned; remove and set aside.',
      'Add broccoli and peppers; stir-fry for 4 minutes until crisp-tender.',
      'Return beef to the pan, add soy sauce and minced ginger; toss for 2 minutes.',
      'Serve immediately over steamed rice.',
    ],
    cookTime: 20,
    difficulty: 'Easy',
  },
  {
    id: 'd12',
    name: 'Pan-Seared Cod',
    slot: 'dinner',
    ingredients: ['cod fillet', 'lemon', 'garlic', 'olive oil', 'asparagus', 'baby potatoes'],
    macros: { calories: 420, protein: 38, carbs: 28, fat: 16 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: [],
    cookingSteps: [
      'Boil baby potatoes in salted water for 15 minutes until fork-tender; drain and halve.',
      'Trim asparagus ends and blanch in boiling water for 3 minutes; drain and set aside.',
      'Pat cod fillets dry and season both sides with salt and pepper.',
      'Heat olive oil in a pan over medium-high heat for 1 minute; sear cod 4 minutes per side until flaky.',
      'In the same pan, sauté minced garlic for 30 seconds, then add asparagus and potatoes.',
      'Squeeze fresh lemon juice over everything and serve immediately.',
    ],
    cookTime: 25,
    difficulty: 'Easy',
  },
  {
    id: 'd13',
    name: 'Veggie Lasagna',
    slot: 'dinner',
    ingredients: ['lasagna sheets', 'zucchini', 'ricotta', 'mozzarella', 'tomato sauce', 'spinach'],
    macros: { calories: 540, protein: 22, carbs: 62, fat: 22 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy'],
    cookingSteps: [
      'Preheat oven to 180°C and lightly oil a baking dish.',
      'Slice zucchini into thin rounds and wilt spinach in a pan over medium heat for 2 minutes.',
      'Mix ricotta with salt, pepper, and a handful of mozzarella in a bowl.',
      'Spread a thin layer of tomato sauce on the bottom of the baking dish.',
      'Layer lasagna sheets, ricotta mixture, zucchini, spinach, and tomato sauce; repeat twice.',
      'Top with remaining mozzarella and cover with foil; bake for 40 minutes.',
      'Remove foil and bake 10 more minutes until golden; rest 10 minutes before slicing.',
    ],
    cookTime: 60,
    difficulty: 'Hard',
  },
  {
    id: 'd14',
    name: 'Lamb Souvlaki',
    slot: 'dinner',
    ingredients: ['lamb', 'pita', 'tzatziki', 'tomato', 'red onion', 'lemon'],
    macros: { calories: 600, protein: 44, carbs: 28, fat: 32 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy'],
    cookingSteps: [
      'Cut lamb into 2 cm cubes and marinate with olive oil, lemon juice, oregano, salt, and pepper for 30 minutes.',
      'Thread lamb onto skewers and grill over high heat for 10 minutes, turning every 2 minutes.',
      'Warm pita bread on the grill for 1 minute per side until soft and lightly charred.',
      'Slice tomato and thinly slice red onion for topping.',
      'Spread tzatziki inside each pita half.',
      'Fill with grilled lamb, tomato, and onion; squeeze extra lemon over the top and serve.',
    ],
    cookTime: 40,
    difficulty: 'Medium',
  },
  {
    id: 'd15',
    name: 'Cauliflower Steak',
    slot: 'dinner',
    ingredients: ['cauliflower', 'tahini', 'pomegranate seeds', 'parsley', 'olive oil'],
    macros: { calories: 380, protein: 14, carbs: 32, fat: 22 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean', 'keto'],
    excludesAllergies: ['nuts'],
    cookingSteps: [
      'Preheat oven to 200°C and line a baking tray with parchment paper.',
      'Cut cauliflower into 2 cm thick steaks from the center of the head; brush both sides with olive oil.',
      'Season with salt and pepper and roast for 25 minutes, flipping halfway, until golden and tender.',
      'Whisk tahini with lemon juice, water, and a pinch of salt to make a smooth sauce.',
      'Plate the cauliflower steaks and drizzle generously with tahini sauce.',
      'Garnish with pomegranate seeds and chopped parsley; serve warm.',
    ],
    cookTime: 30,
    difficulty: 'Medium',
  },
  {
    id: 'd16',
    name: 'Pork Tenderloin',
    slot: 'dinner',
    ingredients: ['pork tenderloin', 'apple', 'rosemary', 'sweet potato', 'olive oil'],
    macros: { calories: 510, protein: 42, carbs: 24, fat: 24 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: [],
    cookingSteps: [
      'Peel and cube sweet potato; toss with olive oil and roast at 200°C for 25 minutes.',
      'Season pork tenderloin with salt, pepper, and chopped rosemary on all sides.',
      'Sear pork in a hot ovenproof pan over medium-high heat for 3 minutes per side until browned.',
      'Transfer pan to the oven and roast at 200°C for 15 minutes until internal temperature reaches 63°C.',
      'Core and slice apple; sauté in the pan with remaining rosemary for 3 minutes until softened.',
      'Rest pork for 5 minutes, slice, and serve with roasted sweet potato and sautéed apple.',
    ],
    cookTime: 35,
    difficulty: 'Medium',
  },
  {
    id: 'd17',
    name: 'Black Bean Chili',
    slot: 'dinner',
    ingredients: ['black beans', 'tomatoes', 'corn', 'onion', 'bell peppers', 'cumin', 'chili powder'],
    macros: { calories: 460, protein: 22, carbs: 68, fat: 8 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan'],
    excludesAllergies: [],
    cookingSteps: [
      'Dice onion and bell peppers into small, even pieces.',
      'Heat olive oil in a large pot over medium heat for 1 minute; sauté onion and peppers for 5 minutes.',
      'Stir in cumin and chili powder; cook for 1 minute until fragrant.',
      'Add drained black beans, diced tomatoes, and corn to the pot.',
      'Pour in 1 cup of water, bring to a boil, then reduce heat and simmer for 25 minutes.',
      'Stir occasionally and mash some beans against the side of the pot to thicken the chili.',
      'Season with salt and pepper and serve hot.',
    ],
    cookTime: 35,
    difficulty: 'Easy',
  },
  {
    id: 's8',
    name: 'Boiled Egg & Crackers',
    slot: 'snack',
    ingredients: ['boiled eggs', 'whole grain crackers', 'salt', 'pepper'],
    macros: { calories: 220, protein: 14, carbs: 16, fat: 10 },
    dietTypes: ['omnivore', 'vegetarian'],
    excludesAllergies: ['gluten', 'eggs'],
    cookingSteps: [
      'Place eggs in a small pot and cover with cold water by 2 cm.',
      'Bring to a boil over medium-high heat, then cover and remove from heat.',
      'Let eggs sit covered for 9 minutes for firm yolks.',
      'Transfer eggs to an ice bath for 3 minutes, then peel carefully.',
      'Halve eggs, season with salt and pepper, and serve with whole grain crackers.',
    ],
    cookTime: 10,
    difficulty: 'Easy',
  },
  {
    id: 's9',
    name: 'Trail Mix',
    slot: 'snack',
    ingredients: ['almonds', 'cashews', 'dried cranberries', 'dark chocolate chips'],
    macros: { calories: 280, protein: 8, carbs: 28, fat: 16 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['nuts'],
    cookingSteps: [
      'Measure equal portions of almonds and cashews into a small bowl.',
      'Add dried cranberries and dark chocolate chips to the mix.',
      'Toss all ingredients together until evenly distributed.',
      'Portion into a single serving and enjoy immediately.',
    ],
    cookTime: 2,
    difficulty: 'Easy',
  },
  {
    id: 's10',
    name: 'Greek Yogurt Parfait',
    slot: 'snack',
    ingredients: ['Greek yogurt', 'granola', 'strawberries', 'honey'],
    macros: { calories: 260, protein: 18, carbs: 32, fat: 6 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'nuts'],
    cookingSteps: [
      'Wash and hull strawberries, then slice them into thin pieces.',
      'Spoon half the Greek yogurt into a glass or jar as the bottom layer.',
      'Add a layer of granola and half the sliced strawberries.',
      'Repeat with remaining yogurt, granola, and strawberries.',
      'Drizzle honey over the top and serve immediately.',
    ],
    cookTime: 5,
    difficulty: 'Easy',
  },
  {
    id: 's11',
    name: 'Avocado on Toast',
    slot: 'snack',
    ingredients: ['whole grain toast', 'avocado', 'lemon', 'chili flakes'],
    macros: { calories: 260, protein: 8, carbs: 26, fat: 16 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['gluten'],
    cookingSteps: [
      'Toast whole grain bread until golden and crisp, about 2 minutes.',
      'Halve the avocado, remove the pit, and scoop the flesh into a bowl.',
      'Mash avocado with lemon juice, salt, and pepper until smooth but slightly chunky.',
      'Spread mashed avocado generously over the warm toast.',
      'Sprinkle chili flakes on top and serve immediately.',
    ],
    cookTime: 5,
    difficulty: 'Easy',
  },
  {
    id: 's12',
    name: 'Protein Bar Homemade',
    slot: 'snack',
    ingredients: ['oats', 'peanut butter', 'protein powder', 'honey', 'dark chocolate'],
    macros: { calories: 230, protein: 14, carbs: 24, fat: 8 },
    dietTypes: ['omnivore', 'vegetarian'],
    excludesAllergies: ['nuts'],
    cookingSteps: [
      'Line a small baking dish with parchment paper.',
      'Warm peanut butter and honey in a microwave for 30 seconds until pourable.',
      'Stir in oats and protein powder until a thick, sticky mixture forms.',
      'Press the mixture firmly and evenly into the prepared dish.',
      'Melt dark chocolate and spread over the top in a thin layer.',
      'Refrigerate for 15 minutes until set, then cut into bars and serve.',
    ],
    cookTime: 20,
    difficulty: 'Easy',
  },
  {
    id: 's13',
    name: 'Edamame Bowl',
    slot: 'snack',
    ingredients: ['edamame pods', 'sea salt'],
    macros: { calories: 180, protein: 14, carbs: 16, fat: 6 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: [],
    cookingSteps: [
      'Bring a pot of salted water to a rolling boil over high heat.',
      'Add edamame pods and cook for 5 minutes until bright green and tender.',
      'Drain edamame in a colander and shake off excess water.',
      'Transfer to a bowl and sprinkle generously with sea salt.',
      'Serve warm or at room temperature.',
    ],
    cookTime: 8,
    difficulty: 'Easy',
  },
  {
    id: 's14',
    name: 'Banana with Peanut Butter',
    slot: 'snack',
    ingredients: ['banana', 'peanut butter', 'chia seeds'],
    macros: { calories: 290, protein: 8, carbs: 36, fat: 12 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan'],
    excludesAllergies: ['nuts'],
    cookingSteps: [
      'Peel the banana and place it on a plate.',
      'Spread peanut butter evenly along the length of the banana.',
      'Sprinkle chia seeds over the peanut butter while it is still tacky.',
      'Slice the banana into rounds and serve immediately.',
    ],
    cookTime: 3,
    difficulty: 'Easy',
  },
  {
    id: 's15',
    name: 'Caprese Skewers',
    slot: 'snack',
    ingredients: ['mozzarella balls', 'cherry tomatoes', 'basil', 'olive oil', 'balsamic'],
    macros: { calories: 220, protein: 12, carbs: 8, fat: 16 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean', 'keto'],
    excludesAllergies: ['dairy'],
    cookingSteps: [
      'Drain mozzarella balls and pat dry with a paper towel.',
      'Wash cherry tomatoes and pick fresh basil leaves of similar size.',
      'Thread a tomato, folded basil leaf, and mozzarella ball onto each small skewer.',
      'Arrange skewers on a plate in a single layer.',
      'Drizzle with olive oil and balsamic vinegar just before serving.',
    ],
    cookTime: 8,
    difficulty: 'Easy',
  },
  {
    id: 's16',
    name: 'Cucumber Roll-ups',
    slot: 'snack',
    ingredients: ['cucumber slices', 'hummus', 'smoked turkey', 'paprika'],
    macros: { calories: 160, protein: 10, carbs: 12, fat: 8 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: [],
    cookingSteps: [
      'Use a vegetable peeler or mandoline to slice cucumber lengthwise into thin, wide strips.',
      'Lay cucumber strips flat on a clean surface and pat dry with a paper towel.',
      'Spread a thin layer of hummus over each cucumber strip.',
      'Place a small piece of smoked turkey at one end of each strip.',
      'Roll tightly from the turkey end and secure with a toothpick if needed.',
      'Sprinkle with paprika and serve chilled.',
    ],
    cookTime: 8,
    difficulty: 'Easy',
  },
  {
    id: 'b17',
    name: 'French Toast',
    slot: 'breakfast',
    ingredients: ['bread', 'eggs', 'milk', 'cinnamon', 'maple syrup', 'butter'],
    macros: { calories: 460, protein: 18, carbs: 58, fat: 18 },
    dietTypes: ['omnivore', 'vegetarian'],
    excludesAllergies: ['nuts'],
    cookingSteps: [
      'Whisk 2 eggs, ½ cup milk, 1 tsp cinnamon, and a pinch of salt in a wide shallow bowl.',
      'Heat a 10-inch non-stick skillet over medium heat and melt 1 tbsp butter until foaming.',
      'Dip each bread slice in the egg mixture for 20 seconds per side until soaked but not falling apart.',
      'Place soaked bread in the skillet and cook 3 minutes per side until golden brown and set in the center.',
      'Transfer to a warm plate and repeat with remaining slices, adding butter as needed.',
      'Drizzle with maple syrup and serve immediately while hot.',
    ],
    cookTime: 15,
    difficulty: 'Easy',
  },
  {
    id: 'b18',
    name: 'Acai Bowl',
    slot: 'breakfast',
    ingredients: ['acai puree', 'banana', 'granola', 'almond butter', 'coconut flakes'],
    macros: { calories: 410, protein: 10, carbs: 68, fat: 12 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan'],
    excludesAllergies: ['dairy', 'eggs'],
    cookingSteps: [
      'Break frozen acai puree into chunks and blend with half a banana and 2 tbsp water until thick and smooth.',
      'Pour the acai base into a chilled bowl and spread evenly with the back of a spoon.',
      'Slice the remaining banana into thin rounds and arrange on one side of the bowl.',
      'Sprinkle granola over the opposite side for contrasting texture.',
      'Drizzle almond butter in thin lines across the top using a warm spoon.',
      'Finish with a light sprinkle of coconut flakes and serve immediately.',
    ],
    cookTime: 10,
    difficulty: 'Easy',
  },
  {
    id: 'b19',
    name: 'Eggs Benedict',
    slot: 'breakfast',
    ingredients: ['eggs', 'English muffins', 'ham', 'hollandaise', 'spinach'],
    macros: { calories: 520, protein: 28, carbs: 36, fat: 28 },
    dietTypes: ['omnivore'],
    excludesAllergies: ['nuts'],
    cookingSteps: [
      'Split English muffins and toast in a toaster or under the broiler until golden, about 2 minutes.',
      'Bring a medium saucepan of water to a gentle simmer (not boiling); stir in 1 tbsp vinegar.',
      'Crack each egg into a small cup and slide into the simmering water; poach 3–4 minutes until whites are set.',
      'Warm ham slices in a skillet over medium heat for 1 minute per side until lightly browned.',
      'Wilt spinach in the same pan for 30 seconds with a splash of water; drain excess moisture.',
      'Whisk hollandaise over a double boiler over low heat until warm and pourable, about 3 minutes.',
      'Stack muffin halves with spinach, ham, and a poached egg; spoon hollandaise over each and serve at once.',
    ],
    cookTime: 25,
    difficulty: 'Hard',
  },
  {
    id: 'b20',
    name: 'Overnight Oats',
    slot: 'breakfast',
    ingredients: ['oats', 'almond milk', 'chia seeds', 'banana', 'peanut butter'],
    macros: { calories: 380, protein: 14, carbs: 58, fat: 12 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan'],
    excludesAllergies: ['gluten', 'dairy', 'eggs'],
    cookingSteps: [
      'Combine ½ cup rolled oats, ¾ cup almond milk, and 1 tbsp chia seeds in a jar or bowl.',
      'Stir thoroughly with a spoon to distribute chia seeds and prevent clumping.',
      'Add a pinch of salt and stir again; seal the jar with a lid.',
      'Refrigerate overnight or for at least 6 hours until oats are soft and creamy.',
      'In the morning, slice banana and fold half into the oats.',
      'Top with a dollop of peanut butter and remaining banana slices; serve cold or at room temperature.',
    ],
    cookTime: 5,
    difficulty: 'Easy',
  },
  {
    id: 'b21',
    name: 'Shakshuka',
    slot: 'breakfast',
    ingredients: ['eggs', 'tomatoes', 'bell peppers', 'onion', 'paprika', 'feta'],
    macros: { calories: 380, protein: 22, carbs: 24, fat: 22 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean'],
    excludesAllergies: ['gluten', 'nuts'],
    cookingSteps: [
      'Dice onion and bell peppers; heat 2 tbsp olive oil in a 10-inch cast-iron skillet over medium heat.',
      'Sauté onion and peppers for 5 minutes until softened, then add 2 tsp paprika and cook 30 seconds.',
      'Pour in crushed tomatoes, season with salt and pepper, and simmer uncovered for 10 minutes until thickened.',
      'Use a spoon to make 4 wells in the sauce and crack an egg into each well.',
      'Cover the skillet and cook over medium-low heat for 6–8 minutes until egg whites are set but yolks are still runny.',
      'Crumble feta over the top, garnish with fresh herbs if desired, and serve straight from the pan with bread on the side.',
    ],
    cookTime: 25,
    difficulty: 'Medium',
  },
  {
    id: 'b22',
    name: 'Quinoa Breakfast Bowl',
    slot: 'breakfast',
    ingredients: ['quinoa', 'milk', 'banana', 'walnuts', 'honey', 'cinnamon'],
    macros: { calories: 420, protein: 16, carbs: 58, fat: 14 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean'],
    excludesAllergies: ['gluten', 'eggs'],
    cookingSteps: [
      'Rinse ½ cup quinoa under cold water; combine with 1 cup milk in a small saucepan over medium-high heat.',
      'Bring to a boil, then reduce heat to low, cover, and simmer for 15 minutes until liquid is absorbed.',
      'Remove from heat, fluff with a fork, and stir in ½ tsp cinnamon.',
      'Transfer quinoa to a bowl and slice banana into rounds on top.',
      'Roughly chop walnuts and scatter over the bowl.',
      'Drizzle with honey and serve warm.',
    ],
    cookTime: 20,
    difficulty: 'Easy',
  },
  {
    id: 'b23',
    name: 'Spinach Mushroom Frittata',
    slot: 'breakfast',
    ingredients: ['eggs', 'spinach', 'mushrooms', 'feta', 'olive oil', 'onion'],
    macros: { calories: 380, protein: 26, carbs: 8, fat: 26 },
    dietTypes: ['omnivore', 'vegetarian', 'keto', 'mediterranean'],
    excludesAllergies: ['gluten', 'nuts'],
    cookingSteps: [
      'Preheat oven to 180°C. Whisk 6 eggs with salt and pepper in a large bowl.',
      'Heat 1 tbsp olive oil in a 10-inch oven-safe skillet over medium heat.',
      'Sauté diced onion for 3 minutes, then add sliced mushrooms and cook 5 minutes until golden.',
      'Add a handful of spinach and stir until wilted, about 1 minute; spread mixture evenly in the pan.',
      'Pour eggs over the vegetables and crumble feta on top; cook without stirring for 2 minutes on the stovetop.',
      'Transfer skillet to the oven and bake for 12–15 minutes until the center is set and lightly golden.',
      'Rest 3 minutes before slicing into wedges and serving.',
    ],
    cookTime: 25,
    difficulty: 'Medium',
  },
  {
    id: 'b24',
    name: 'Peanut Butter Toast',
    slot: 'breakfast',
    ingredients: ['whole grain bread', 'peanut butter', 'banana', 'chia seeds'],
    macros: { calories: 380, protein: 16, carbs: 42, fat: 18 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan'],
    excludesAllergies: ['dairy', 'eggs'],
    cookingSteps: [
      'Toast 2 slices of whole grain bread in a toaster until golden and crisp, about 2–3 minutes.',
      'Spread 2 tbsp peanut butter evenly on each warm slice while the bread is still hot.',
      'Peel and slice banana into thin rounds.',
      'Arrange banana slices in overlapping rows on top of the peanut butter.',
      'Sprinkle chia seeds over the banana and serve immediately.',
    ],
    cookTime: 5,
    difficulty: 'Easy',
  },
  {
    id: 'l18',
    name: 'Chicken Burrito',
    slot: 'lunch',
    ingredients: ['chicken', 'tortilla', 'black beans', 'rice', 'cheese', 'salsa'],
    macros: { calories: 580, protein: 38, carbs: 58, fat: 20 },
    dietTypes: ['omnivore'],
    excludesAllergies: ['nuts', 'eggs'],
    cookingSteps: [
      'Season chicken breast with cumin, salt, and pepper; grill or pan-sear in a skillet over medium-high heat for 6 minutes per side.',
      'Rest chicken 3 minutes, then slice into thin strips.',
      'Warm cooked rice and black beans separately in a small pan over low heat for 3 minutes.',
      'Heat tortillas in a dry skillet over medium heat for 30 seconds per side until pliable.',
      'Layer rice, beans, chicken, and shredded cheese down the center of each tortilla.',
      'Top with salsa, fold in the sides, roll tightly, and serve cut in half on the diagonal.',
    ],
    cookTime: 25,
    difficulty: 'Easy',
  },
  {
    id: 'l19',
    name: 'Cobb Salad',
    slot: 'lunch',
    ingredients: ['chicken', 'bacon', 'eggs', 'avocado', 'blue cheese', 'tomatoes', 'lettuce'],
    macros: { calories: 510, protein: 38, carbs: 12, fat: 32 },
    dietTypes: ['omnivore', 'keto', 'mediterranean'],
    excludesAllergies: ['gluten', 'nuts'],
    cookingSteps: [
      'Hard-boil 2 eggs in simmering water for 10 minutes; cool in ice water, peel, and quarter.',
      'Cook bacon in a skillet over medium heat for 6 minutes until crisp; drain on paper towels and crumble.',
      'Grill or pan-sear seasoned chicken breast over medium-high heat for 6 minutes per side; slice into strips.',
      'Wash and chop romaine lettuce into bite-sized pieces and arrange as the base in a large bowl.',
      'Arrange rows of sliced chicken, crumbled bacon, diced tomatoes, avocado slices, and blue cheese on top.',
      'Place egg quarters between the rows and serve with dressing on the side or drizzled just before eating.',
    ],
    cookTime: 25,
    difficulty: 'Easy',
  },
  {
    id: 'l20',
    name: 'Veggie Stir-Fry',
    slot: 'lunch',
    ingredients: ['mixed vegetables', 'brown rice', 'soy sauce', 'garlic', 'ginger', 'sesame oil'],
    macros: { calories: 420, protein: 14, carbs: 58, fat: 14 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan'],
    excludesAllergies: ['gluten', 'dairy', 'nuts', 'eggs'],
    cookingSteps: [
      'Cook brown rice according to package instructions and keep warm.',
      'Prep mixed vegetables into uniform bite-sized pieces; mince garlic and ginger.',
      'Heat 1 tbsp sesame oil in a wok or large skillet over high heat for 1 minute until shimmering.',
      'Add garlic and ginger; stir-fry 30 seconds until fragrant.',
      'Add vegetables in order of density (carrots first, leafy greens last) and stir-fry 5–6 minutes until crisp-tender.',
      'Pour in 2 tbsp soy sauce and toss for 1 minute to coat evenly.',
      'Serve immediately over steamed brown rice.',
    ],
    cookTime: 20,
    difficulty: 'Easy',
  },
  {
    id: 'l21',
    name: 'Salmon Poke Bowl',
    slot: 'lunch',
    ingredients: ['salmon', 'sushi rice', 'edamame', 'avocado', 'cucumber', 'soy sauce'],
    macros: { calories: 540, protein: 36, carbs: 58, fat: 16 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'nuts', 'eggs'],
    cookingSteps: [
      'Cook sushi rice according to package instructions; season with rice vinegar and cool to room temperature.',
      'Dice sashimi-grade salmon into 1 cm cubes and toss with 1 tbsp soy sauce and sesame oil in a bowl.',
      'Slice cucumber into thin half-moons and dice avocado into cubes.',
      'Blanch edamame in boiling salted water for 3 minutes; drain and shell if using pods.',
      'Divide rice among bowls and top with salmon, edamame, cucumber, and avocado in separate sections.',
      'Drizzle with remaining soy sauce and serve immediately.',
    ],
    cookTime: 25,
    difficulty: 'Medium',
  },
  {
    id: 'l22',
    name: 'Lentil Curry',
    slot: 'lunch',
    ingredients: ['red lentils', 'coconut milk', 'curry powder', 'tomatoes', 'rice', 'onion'],
    macros: { calories: 480, protein: 20, carbs: 62, fat: 14 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan'],
    excludesAllergies: ['gluten', 'dairy', 'nuts', 'eggs'],
    cookingSteps: [
      'Rinse red lentils under cold water until the water runs clear.',
      'Cook rice according to package instructions and keep warm.',
      'Heat 1 tbsp oil in a medium pot over medium heat; sauté diced onion for 4 minutes until translucent.',
      'Stir in 2 tbsp curry powder and cook 1 minute until fragrant.',
      'Add lentils, diced tomatoes, and 2 cups water; bring to a boil, then simmer covered for 20 minutes.',
      'Stir in coconut milk and simmer uncovered for 5 more minutes until lentils are soft and creamy.',
      'Season with salt and serve over steamed rice.',
    ],
    cookTime: 30,
    difficulty: 'Easy',
  },
  {
    id: 'l23',
    name: 'Chicken Wrap',
    slot: 'lunch',
    ingredients: ['chicken', 'tortilla', 'hummus', 'lettuce', 'tomato', 'cucumber'],
    macros: { calories: 480, protein: 36, carbs: 42, fat: 18 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['dairy', 'nuts', 'eggs'],
    cookingSteps: [
      'Season chicken breast with salt, pepper, and paprika; grill or pan-sear over medium-high heat for 6 minutes per side.',
      'Rest chicken 3 minutes, then slice into thin strips across the grain.',
      'Warm tortillas in a dry skillet over medium heat for 20 seconds per side until flexible.',
      'Spread 2 tbsp hummus evenly over each tortilla, leaving a 2 cm border at the edges.',
      'Layer lettuce, sliced tomato, cucumber rounds, and chicken strips down the center.',
      'Fold in the sides and roll tightly from the bottom; slice in half diagonally and serve.',
    ],
    cookTime: 15,
    difficulty: 'Easy',
  },
  {
    id: 'l24',
    name: 'Caprese Sandwich',
    slot: 'lunch',
    ingredients: ['ciabatta', 'mozzarella', 'tomatoes', 'basil', 'pesto', 'olive oil'],
    macros: { calories: 460, protein: 22, carbs: 52, fat: 18 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean'],
    excludesAllergies: ['nuts', 'eggs'],
    cookingSteps: [
      'Slice ciabatta horizontally and lightly toast cut sides under a broiler for 2 minutes until crisp.',
      'Slice tomatoes and fresh mozzarella into ¼-inch rounds of similar size.',
      'Spread pesto on the bottom half of the bread in an even layer.',
      'Layer tomato and mozzarella slices alternately, tucking fresh basil leaves between each layer.',
      'Drizzle with olive oil and a pinch of salt and pepper.',
      'Close the sandwich, press gently, and cut in half to serve.',
    ],
    cookTime: 10,
    difficulty: 'Easy',
  },
  {
    id: 'l25',
    name: 'Beef Pho',
    slot: 'lunch',
    ingredients: ['beef', 'rice noodles', 'broth', 'bean sprouts', 'basil', 'lime'],
    macros: { calories: 520, protein: 34, carbs: 68, fat: 8 },
    dietTypes: ['omnivore'],
    excludesAllergies: ['gluten', 'dairy', 'nuts', 'eggs'],
    cookingSteps: [
      'Simmer beef broth with star anise, ginger, and onion in a large pot over low heat for 30 minutes.',
      'Slice raw beef sirloin paper-thin against the grain and set aside.',
      'Cook rice noodles in boiling water for 4 minutes until tender; drain and divide among large bowls.',
      'Arrange raw beef slices on top of the noodles in each bowl.',
      'Bring broth to a rolling boil and ladle hot broth over the beef and noodles to cook the meat instantly.',
      'Top with bean sprouts, Thai basil, and a squeeze of lime; serve immediately.',
    ],
    cookTime: 40,
    difficulty: 'Medium',
  },
  {
    id: 'l26',
    name: 'Spinach Goat Cheese Salad',
    slot: 'lunch',
    ingredients: ['spinach', 'goat cheese', 'walnuts', 'pear', 'balsamic', 'olive oil'],
    macros: { calories: 380, protein: 14, carbs: 18, fat: 28 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean', 'keto'],
    excludesAllergies: ['gluten', 'eggs'],
    cookingSteps: [
      'Wash and dry baby spinach; place in a large salad bowl.',
      'Slice pear into thin wedges and crumble goat cheese into small pieces.',
      'Toast walnuts in a dry skillet over medium heat for 3 minutes, tossing frequently until fragrant.',
      'Whisk balsamic vinegar with olive oil, salt, and pepper in a small bowl.',
      'Add pear, goat cheese, and walnuts to the spinach.',
      'Drizzle dressing over the salad and toss gently; serve immediately.',
    ],
    cookTime: 10,
    difficulty: 'Easy',
  },
  {
    id: 'd18',
    name: 'Roast Chicken with Veggies',
    slot: 'dinner',
    ingredients: ['chicken thighs', 'potatoes', 'carrots', 'rosemary', 'olive oil'],
    macros: { calories: 560, protein: 44, carbs: 32, fat: 24 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'nuts', 'eggs'],
    cookingSteps: [
      'Preheat oven to 200°C. Pat chicken thighs dry and season generously with salt, pepper, and chopped rosemary.',
      'Cut potatoes and carrots into 2 cm chunks and toss with olive oil, salt, and pepper on a large sheet pan.',
      'Nestle chicken thighs skin-side up among the vegetables, leaving space between each piece.',
      'Roast for 40 minutes, turning vegetables once halfway through, until chicken skin is golden and internal temperature reaches 74°C.',
      'Rest chicken for 5 minutes before serving alongside the roasted vegetables.',
    ],
    cookTime: 60,
    difficulty: 'Medium',
  },
  {
    id: 'd19',
    name: 'Vegetable Paella',
    slot: 'dinner',
    ingredients: ['rice', 'saffron', 'bell peppers', 'peas', 'artichokes', 'lemon'],
    macros: { calories: 490, protein: 14, carbs: 72, fat: 14 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'nuts', 'eggs'],
    cookingSteps: [
      'Steep a pinch of saffron in ½ cup warm vegetable broth for 10 minutes.',
      'Heat 2 tbsp olive oil in a 12-inch paella pan or wide skillet over medium heat.',
      'Sauté diced bell peppers for 4 minutes, then add rice and stir to coat for 2 minutes.',
      'Pour in saffron broth and 2 cups additional broth; bring to a simmer without stirring.',
      'Cook uncovered over medium-low heat for 18 minutes until rice is nearly tender.',
      'Scatter peas and artichoke hearts over the top; cook 5 more minutes until rice is al dente and liquid is absorbed.',
      'Rest 5 minutes, garnish with lemon wedges, and serve from the pan.',
    ],
    cookTime: 45,
    difficulty: 'Medium',
  },
  {
    id: 'd20',
    name: 'Steak with Sweet Potato',
    slot: 'dinner',
    ingredients: ['ribeye steak', 'sweet potato', 'asparagus', 'butter', 'garlic'],
    macros: { calories: 620, protein: 48, carbs: 42, fat: 26 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['gluten', 'nuts', 'eggs'],
    cookingSteps: [
      'Pierce sweet potato and microwave or bake at 200°C for 25 minutes until fork-tender; split open and keep warm.',
      'Season ribeye generously with salt and pepper; let sit at room temperature for 15 minutes.',
      'Heat a cast-iron skillet over high heat for 2 minutes until smoking; sear steak 4 minutes per side for medium-rare.',
      'Rest steak on a cutting board for 5 minutes, tented with foil.',
      'In the same pan over medium heat, melt butter with minced garlic for 1 minute.',
      'Blanch asparagus in boiling salted water for 3 minutes; toss in garlic butter.',
      'Slice steak against the grain and serve with sweet potato and asparagus.',
    ],
    cookTime: 35,
    difficulty: 'Medium',
  },
  {
    id: 'd21',
    name: 'Thai Green Curry',
    slot: 'dinner',
    ingredients: ['chicken', 'coconut milk', 'green curry paste', 'bamboo shoots', 'jasmine rice', 'basil'],
    macros: { calories: 520, protein: 32, carbs: 48, fat: 22 },
    dietTypes: ['omnivore'],
    excludesAllergies: ['gluten', 'dairy', 'nuts', 'eggs'],
    cookingSteps: [
      'Cook jasmine rice according to package instructions and keep warm.',
      'Cut chicken into bite-sized pieces and set aside.',
      'Heat 1 tbsp oil in a wok or large pot over medium-high heat; fry green curry paste for 1 minute until fragrant.',
      'Add thick coconut milk from the top of the can and stir until the paste dissolves, about 2 minutes.',
      'Add chicken pieces and simmer for 10 minutes until nearly cooked through.',
      'Stir in remaining coconut milk and drained bamboo shoots; simmer 5 more minutes until chicken is tender.',
      'Tear fresh Thai basil leaves over the curry and serve over jasmine rice.',
    ],
    cookTime: 30,
    difficulty: 'Medium',
  },
  {
    id: 'd22',
    name: 'Eggplant Parmigiana',
    slot: 'dinner',
    ingredients: ['eggplant', 'mozzarella', 'parmesan', 'tomato sauce', 'basil', 'breadcrumbs'],
    macros: { calories: 490, protein: 22, carbs: 42, fat: 26 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean'],
    excludesAllergies: ['eggs'],
    cookingSteps: [
      'Slice eggplant into ½-inch rounds, salt both sides, and rest 20 minutes; pat dry with paper towels.',
      'Set up three stations: flour, beaten eggs, and breadcrumbs mixed with parmesan.',
      'Dredge each eggplant slice through flour, egg, and breadcrumbs; press coating firmly.',
      'Shallow-fry in ¼ inch of oil in a large skillet over medium heat for 3 minutes per side until golden; drain on a rack.',
      'Preheat oven to 190°C. Spread tomato sauce in the bottom of a baking dish.',
      'Layer fried eggplant, mozzarella slices, and basil; repeat layers and top with parmesan.',
      'Bake uncovered for 25 minutes until cheese is bubbling and golden; rest 10 minutes before serving.',
    ],
    cookTime: 60,
    difficulty: 'Hard',
  },
  {
    id: 'd23',
    name: 'Tuna Steak',
    slot: 'dinner',
    ingredients: ['tuna steak', 'sesame seeds', 'soy sauce', 'ginger', 'bok choy', 'rice'],
    macros: { calories: 460, protein: 44, carbs: 22, fat: 22 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'nuts', 'eggs'],
    cookingSteps: [
      'Cook rice according to package instructions and keep warm.',
      'Pat tuna steaks dry and press sesame seeds onto both sides to coat evenly.',
      'Heat a cast-iron or stainless skillet over high heat for 2 minutes until very hot.',
      'Sear tuna 90 seconds per side for rare, or 2 minutes per side for medium; remove and rest 3 minutes.',
      'In the same pan over medium heat, stir-fry halved bok choy with minced ginger for 3 minutes until wilted.',
      'Slice tuna against the grain into ½-inch pieces and serve over rice with bok choy and a drizzle of soy sauce.',
    ],
    cookTime: 25,
    difficulty: 'Medium',
  },
  {
    id: 'd24',
    name: 'Vegan Burger',
    slot: 'dinner',
    ingredients: ['black bean patty', 'whole wheat bun', 'lettuce', 'tomato', 'vegan mayo', 'pickles'],
    macros: { calories: 480, protein: 22, carbs: 56, fat: 18 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan'],
    excludesAllergies: ['dairy', 'nuts', 'eggs'],
    cookingSteps: [
      'Mash black beans with breadcrumbs, onion, and spices; form into 2 patties about 1 cm thick.',
      'Heat 1 tbsp oil in a skillet over medium heat; cook patties 5 minutes per side until a crust forms and centers are heated through.',
      'Split whole wheat buns and toast cut sides in the same pan for 1 minute until lightly golden.',
      'Slice tomato and separate lettuce leaves; drain pickle slices.',
      'Spread vegan mayo on both bun halves.',
      'Stack lettuce, patty, tomato, and pickles on the bottom bun; close and serve immediately.',
    ],
    cookTime: 30,
    difficulty: 'Medium',
  },
  {
    id: 'd25',
    name: 'Pork Schnitzel',
    slot: 'dinner',
    ingredients: ['pork loin', 'breadcrumbs', 'egg', 'lemon', 'potatoes', 'parsley'],
    macros: { calories: 580, protein: 42, carbs: 42, fat: 26 },
    dietTypes: ['omnivore'],
    excludesAllergies: ['dairy', 'nuts'],
    cookingSteps: [
      'Peel and boil potatoes in salted water for 18 minutes until fork-tender; drain and mash with butter or keep whole.',
      'Pound pork loin cutlets to ¼-inch thickness between plastic wrap using a meat mallet.',
      'Set up dredging stations: flour, beaten egg, and seasoned breadcrumbs.',
      'Coat each cutlet in flour, dip in egg, then press into breadcrumbs on both sides.',
      'Heat ¼ inch of oil in a large skillet over medium-high heat; fry schnitzel 3 minutes per side until golden and cooked through.',
      'Drain on paper towels, squeeze fresh lemon over the top, and garnish with chopped parsley; serve with potatoes.',
    ],
    cookTime: 35,
    difficulty: 'Medium',
  },
  {
    id: 'd26',
    name: 'Mushroom Risotto',
    slot: 'dinner',
    ingredients: ['arborio rice', 'mushrooms', 'parmesan', 'onion', 'white wine', 'butter'],
    macros: { calories: 520, protein: 14, carbs: 72, fat: 18 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean'],
    excludesAllergies: ['gluten', 'nuts', 'eggs'],
    cookingSteps: [
      'Heat vegetable broth in a separate saucepan and keep at a gentle simmer over low heat.',
      'Sauté sliced mushrooms in 1 tbsp butter in a wide pot over medium-high heat for 5 minutes until golden; set aside.',
      'In the same pot, cook diced onion in olive oil over medium heat for 3 minutes until soft.',
      'Add arborio rice and toast, stirring, for 2 minutes until edges look translucent.',
      'Pour in white wine and stir until absorbed, about 1 minute.',
      'Add warm broth one ladle at a time, stirring constantly and waiting until each addition is absorbed before adding the next, for about 20 minutes.',
      'Fold in mushrooms, remaining butter, and grated parmesan; rest 2 minutes and serve creamy.',
    ],
    cookTime: 45,
    difficulty: 'Hard',
  },
  {
    id: 's17',
    name: 'Dark Chocolate Square',
    slot: 'snack',
    ingredients: ['dark chocolate 70%'],
    macros: { calories: 170, protein: 3, carbs: 14, fat: 12 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean', 'keto'],
    excludesAllergies: ['gluten', 'dairy', 'nuts', 'eggs'],
    cookingSteps: [
      'Break a bar of 70% dark chocolate into individual squares along the scored lines.',
      'Place one or two squares on a small plate at room temperature.',
      'Allow chocolate to sit for 1 minute so it softens slightly on the surface.',
      'Enjoy slowly, letting each piece melt on the tongue for full flavor.',
    ],
    cookTime: 1,
    difficulty: 'Easy',
  },
  {
    id: 's18',
    name: 'Almond Date Energy Balls',
    slot: 'snack',
    ingredients: ['dates', 'almonds', 'cocoa powder', 'coconut oil'],
    macros: { calories: 240, protein: 8, carbs: 28, fat: 12 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'eggs'],
    cookingSteps: [
      'Pit dates and soak in warm water for 5 minutes if very dry; drain well.',
      'Pulse almonds in a food processor until coarsely chopped, about 10 seconds.',
      'Add dates, 1 tbsp cocoa powder, and 1 tsp melted coconut oil; process until a sticky dough forms, about 1 minute.',
      'Roll mixture into 8 equal balls using lightly oiled hands, about 2 cm each.',
      'Roll each ball in extra cocoa powder for coating if desired.',
      'Refrigerate on a plate for 10 minutes to firm up before serving.',
    ],
    cookTime: 15,
    difficulty: 'Easy',
  },
  {
    id: 's19',
    name: 'Greek Yogurt with Walnuts',
    slot: 'snack',
    ingredients: ['Greek yogurt', 'walnuts', 'honey', 'cinnamon'],
    macros: { calories: 240, protein: 18, carbs: 16, fat: 12 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean'],
    excludesAllergies: ['gluten', 'eggs'],
    cookingSteps: [
      'Spoon ¾ cup Greek yogurt into a small bowl.',
      'Roughly chop walnuts into bite-sized pieces.',
      'Scatter walnuts evenly over the yogurt.',
      'Drizzle honey over the top and dust lightly with cinnamon.',
      'Serve immediately or chill for 5 minutes for a firmer texture.',
    ],
    cookTime: 3,
    difficulty: 'Easy',
  },
  {
    id: 's20',
    name: 'Roasted Chickpeas',
    slot: 'snack',
    ingredients: ['chickpeas', 'olive oil', 'paprika', 'cumin', 'salt'],
    macros: { calories: 200, protein: 10, carbs: 28, fat: 6 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'nuts', 'eggs'],
    cookingSteps: [
      'Preheat oven to 200°C. Drain and rinse chickpeas; pat completely dry with a clean kitchen towel.',
      'Toss chickpeas in a bowl with 1 tbsp olive oil, 1 tsp paprika, ½ tsp cumin, and a pinch of salt.',
      'Spread in a single layer on a baking sheet lined with parchment paper.',
      'Roast for 25–30 minutes, shaking the pan every 10 minutes, until chickpeas are crisp and golden.',
      'Cool for 5 minutes on the sheet—they will crisp further as they cool—then serve.',
    ],
    cookTime: 30,
    difficulty: 'Easy',
  },
  {
    id: 's21',
    name: 'Apple with Cheese',
    slot: 'snack',
    ingredients: ['apple', 'cheddar cheese'],
    macros: { calories: 220, protein: 10, carbs: 24, fat: 10 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean', 'keto'],
    excludesAllergies: ['gluten', 'nuts', 'eggs'],
    cookingSteps: [
      'Wash and core an apple; slice into 8 wedges about ½ cm thick.',
      'Cut cheddar cheese into thin slices or small cubes roughly matching the apple wedge size.',
      'Arrange apple wedges and cheese alternately on a plate.',
      'Serve immediately at room temperature for the best flavor contrast.',
    ],
    cookTime: 3,
    difficulty: 'Easy',
  },
  {
    id: 's22',
    name: 'Smoothie Green',
    slot: 'snack',
    ingredients: ['spinach', 'banana', 'protein powder', 'almond milk', 'chia seeds'],
    macros: { calories: 220, protein: 14, carbs: 28, fat: 4 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan'],
    excludesAllergies: ['dairy', 'eggs'],
    cookingSteps: [
      'Add 1 cup almond milk and a handful of spinach to a blender.',
      'Peel and break half a banana into the blender.',
      'Add one scoop of protein powder and 1 tsp chia seeds.',
      'Blend on high speed for 60 seconds until completely smooth and bright green.',
      'Pour into a glass and serve immediately over ice if desired.',
    ],
    cookTime: 5,
    difficulty: 'Easy',
  },
  {
    id: 's23',
    name: 'Olives and Cheese Plate',
    slot: 'snack',
    ingredients: ['kalamata olives', 'feta', 'cherry tomatoes', 'olive oil'],
    macros: { calories: 240, protein: 10, carbs: 4, fat: 22 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean', 'keto'],
    excludesAllergies: ['gluten', 'nuts', 'eggs'],
    cookingSteps: [
      'Drain kalamata olives and pat dry; place in a small serving bowl.',
      'Cut feta into cubes and halve cherry tomatoes.',
      'Arrange olives, feta, and tomatoes on a plate in separate clusters.',
      'Drizzle olive oil over the feta and tomatoes.',
      'Serve at room temperature with toothpicks or small forks.',
    ],
    cookTime: 5,
    difficulty: 'Easy',
  },
  {
    id: 's24',
    name: 'Cottage Cheese with Pineapple',
    slot: 'snack',
    ingredients: ['cottage cheese', 'fresh pineapple', 'cinnamon'],
    macros: { calories: 180, protein: 22, carbs: 18, fat: 2 },
    dietTypes: ['omnivore', 'vegetarian'],
    excludesAllergies: ['gluten', 'nuts', 'eggs'],
    cookingSteps: [
      'Scoop ¾ cup cottage cheese into a small bowl.',
      'Cut fresh pineapple into bite-sized chunks, about ½ cup total.',
      'Fold pineapple pieces gently into the cottage cheese or layer on top.',
      'Dust with a pinch of cinnamon and serve immediately.',
    ],
    cookTime: 3,
    difficulty: 'Easy',
  },
];

/**
 * Returns templates compatible with the user's diet and safe for their allergies.
 *
 * A meal is excluded if the user has an active allergy listed in
 * meal.excludesAllergies. "none" in allergies means no restrictions.
 *
 * @param dietType - User's chosen diet (omnivore, vegan, etc.).
 * @param allergies - Selected allergy tags from onboarding.
 * @returns Filtered subset of MEAL_TEMPLATES.
 */
export function filterTemplates(
  dietType: DietType,
  allergies: string[]
): Meal[] {
  const activeAllergies = (allergies ?? []).filter((a) => a !== 'none');

  return MEAL_TEMPLATES.filter((meal) => {
    if (!meal.dietTypes.includes(dietType)) return false;
    if (activeAllergies.length === 0) return true;
    return !activeAllergies.some((allergy) =>
      meal.excludesAllergies.includes(allergy as Allergy)
    );
  });
}

/**
 * Randomly selects one meal for a slot from the filtered pool.
 *
 * @param pool - Usually output of filterTemplates.
 * @param slot - breakfast | lunch | dinner | snack.
 * @param excludeIds - Meal ids to skip (already on today's plan).
 * @returns Random matching meal or null if pool is empty.
 */
export function pickMealForSlot(
  pool: Meal[],
  slot: MealSlot,
  excludeIds: string[] = []
): Meal | null {
  const candidates = pool.filter(
    (m) => m.slot === slot && !excludeIds.includes(m.id)
  );
  if (candidates.length === 0) return null;
  return candidates[Math.floor(Math.random() * candidates.length)];
}
