import type { Allergy, DietType, Meal, MealSlot } from '@/types';

export const MEAL_TEMPLATES: Meal[] = [
  {
    id: 'b1',
    name: 'Greek Yogurt & Berries',
    slot: 'breakfast',
    ingredients: ['Greek yogurt', 'mixed berries', 'honey'],
    macros: { calories: 320, protein: 22, carbs: 38, fat: 8 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean'],
    excludesAllergies: ['gluten', 'nuts'],
  },
  {
    id: 'b2',
    name: 'Oatmeal with Banana',
    slot: 'breakfast',
    ingredients: ['oats', 'banana', 'almond milk'],
    macros: { calories: 380, protein: 12, carbs: 68, fat: 7 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['dairy', 'eggs', 'gluten'],
  },
  {
    id: 'b3',
    name: 'Scrambled Eggs & Toast',
    slot: 'breakfast',
    ingredients: ['eggs', 'whole wheat bread', 'spinach'],
    macros: { calories: 420, protein: 28, carbs: 32, fat: 18 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['dairy', 'nuts'],
  },
  {
    id: 'b4',
    name: 'Keto Avocado Eggs',
    slot: 'breakfast',
    ingredients: ['eggs', 'avocado', 'olive oil'],
    macros: { calories: 450, protein: 24, carbs: 6, fat: 38 },
    dietTypes: ['omnivore', 'keto'],
    excludesAllergies: ['gluten', 'dairy', 'nuts'],
  },
  {
    id: 'b5',
    name: 'Avocado Toast',
    slot: 'breakfast',
    ingredients: ['sourdough bread', 'avocado', 'lemon juice', 'chili flakes', 'olive oil'],
    macros: { calories: 390, protein: 10, carbs: 42, fat: 22 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['nuts', 'dairy', 'eggs'],
    cookingSteps: [
      'Toast the sourdough bread until golden and crispy.',
      'Halve the avocado, remove the pit, and scoop the flesh into a bowl.',
      'Mash the avocado with lemon juice, salt, and pepper.',
      'Spread the mashed avocado generously over the toast.',
      'Drizzle with olive oil and sprinkle chili flakes on top.',
    ],
    cookTime: 10,
    difficulty: 'Easy',
  },
  {
    id: 'b6',
    name: 'Protein Pancakes',
    slot: 'breakfast',
    ingredients: ['oats', 'banana', 'eggs', 'protein powder', 'cinnamon'],
    macros: { calories: 440, protein: 34, carbs: 48, fat: 10 },
    dietTypes: ['omnivore'],
    excludesAllergies: ['gluten', 'dairy', 'nuts'],
    cookingSteps: [
      'Blend oats, banana, eggs, protein powder, and cinnamon until smooth.',
      'Heat a non-stick pan over medium heat and lightly grease it.',
      'Pour small rounds of batter onto the pan.',
      'Cook for 2-3 minutes until bubbles form, then flip.',
      'Cook another 1-2 minutes until golden. Serve warm.',
    ],
    cookTime: 15,
    difficulty: 'Easy',
  },
  {
    id: 'b7',
    name: 'Greek Omelette',
    slot: 'breakfast',
    ingredients: ['eggs', 'feta cheese', 'spinach', 'tomatoes', 'olive oil'],
    macros: { calories: 380, protein: 26, carbs: 8, fat: 28 },
    dietTypes: ['omnivore', 'vegetarian', 'keto', 'mediterranean'],
    excludesAllergies: ['gluten', 'nuts'],
    cookingSteps: [
      'Whisk 3 eggs with salt and pepper in a bowl.',
      'Heat olive oil in a pan over medium heat.',
      'Add spinach and tomatoes, sauté for 2 minutes.',
      'Pour in the eggs and let them set for 1 minute.',
      'Add crumbled feta, fold the omelette in half, and serve.',
    ],
    cookTime: 10,
    difficulty: 'Easy',
  },
  {
    id: 'b8',
    name: 'Chia Pudding',
    slot: 'breakfast',
    ingredients: ['chia seeds', 'almond milk', 'honey', 'mixed berries', 'vanilla extract'],
    macros: { calories: 310, protein: 10, carbs: 36, fat: 14 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'eggs', 'nuts'],
    cookingSteps: [
      'Mix chia seeds with almond milk and vanilla extract in a jar.',
      'Stir well to prevent clumping.',
      'Add honey and stir again.',
      'Refrigerate overnight or for at least 4 hours.',
      'Top with fresh mixed berries before serving.',
    ],
    cookTime: 5,
    difficulty: 'Easy',
  },
  {
    id: 'l1',
    name: 'Grilled Chicken Salad',
    slot: 'lunch',
    ingredients: ['chicken breast', 'lettuce', 'tomato', 'olive oil'],
    macros: { calories: 480, protein: 42, carbs: 18, fat: 26 },
    dietTypes: ['omnivore', 'keto', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'nuts', 'eggs'],
  },
  {
    id: 'l2',
    name: 'Lentil Soup & Bread',
    slot: 'lunch',
    ingredients: ['lentils', 'carrots', 'celery', 'bread'],
    macros: { calories: 520, protein: 22, carbs: 78, fat: 10 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['dairy', 'nuts', 'eggs'],
  },
  {
    id: 'l3',
    name: 'Tofu Buddha Bowl',
    slot: 'lunch',
    ingredients: ['tofu', 'brown rice', 'broccoli', 'sesame'],
    macros: { calories: 540, protein: 28, carbs: 62, fat: 18 },
    dietTypes: ['vegetarian', 'vegan'],
    excludesAllergies: ['dairy', 'eggs', 'gluten'],
  },
  {
    id: 'l4',
    name: 'Salmon & Quinoa',
    slot: 'lunch',
    ingredients: ['salmon', 'quinoa', 'asparagus'],
    macros: { calories: 580, protein: 38, carbs: 42, fat: 28 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'nuts', 'eggs'],
  },
  {
    id: 'l5',
    name: 'Tuna Niçoise Salad',
    slot: 'lunch',
    ingredients: ['tuna', 'green beans', 'boiled eggs', 'olives', 'cherry tomatoes', 'olive oil'],
    macros: { calories: 460, protein: 38, carbs: 20, fat: 24 },
    dietTypes: ['omnivore', 'mediterranean', 'keto'],
    excludesAllergies: ['gluten', 'dairy', 'nuts'],
    cookingSteps: [
      'Boil green beans for 3 minutes then cool in ice water.',
      'Hard boil eggs for 8 minutes, peel and halve.',
      'Drain tuna and flake into a bowl.',
      'Arrange all ingredients on a plate.',
      'Drizzle with olive oil and season with salt and pepper.',
    ],
    cookTime: 20,
    difficulty: 'Easy',
  },
  {
    id: 'l6',
    name: 'Chicken Souvlaki Bowl',
    slot: 'lunch',
    ingredients: ['chicken breast', 'pita bread', 'tzatziki', 'tomatoes', 'red onion', 'olive oil'],
    macros: { calories: 560, protein: 44, carbs: 46, fat: 18 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['nuts', 'eggs'],
    cookingSteps: [
      'Cut chicken into cubes and marinate with olive oil, lemon, oregano for 30 minutes.',
      'Thread onto skewers and grill on high heat for 10-12 minutes, turning occasionally.',
      'Warm the pita bread on the grill for 1 minute each side.',
      'Slice tomatoes and red onion thinly.',
      'Assemble bowl with pita, chicken, vegetables, and a generous dollop of tzatziki.',
    ],
    cookTime: 45,
    difficulty: 'Medium',
  },
  {
    id: 'l7',
    name: 'Falafel Wrap',
    slot: 'lunch',
    ingredients: ['chickpeas', 'pita bread', 'tahini', 'cucumber', 'tomatoes', 'parsley'],
    macros: { calories: 500, protein: 18, carbs: 66, fat: 18 },
    dietTypes: ['vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['dairy', 'eggs', 'nuts'],
    cookingSteps: [
      'Blend chickpeas with parsley, garlic, cumin, and salt into a rough paste.',
      'Form into small patties and pan-fry in olive oil for 3-4 minutes each side.',
      'Warm pita bread and spread tahini sauce.',
      'Add sliced cucumber and tomatoes.',
      'Place falafel inside, wrap tightly, and serve.',
    ],
    cookTime: 25,
    difficulty: 'Medium',
  },
  {
    id: 'l8',
    name: 'Quinoa Tabbouleh',
    slot: 'lunch',
    ingredients: ['quinoa', 'parsley', 'mint', 'tomatoes', 'cucumber', 'lemon juice', 'olive oil'],
    macros: { calories: 420, protein: 14, carbs: 58, fat: 16 },
    dietTypes: ['vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'eggs', 'nuts'],
    cookingSteps: [
      'Cook quinoa according to package instructions and let cool completely.',
      'Finely chop parsley, mint, tomatoes, and cucumber.',
      'Mix all vegetables with cooled quinoa in a large bowl.',
      'Dress with lemon juice, olive oil, salt, and pepper.',
      'Toss well and refrigerate for 30 minutes before serving.',
    ],
    cookTime: 40,
    difficulty: 'Easy',
  },
  {
    id: 'd1',
    name: 'Turkey Stir-Fry',
    slot: 'dinner',
    ingredients: ['turkey', 'peppers', 'rice noodles'],
    macros: { calories: 520, protein: 36, carbs: 58, fat: 14 },
    dietTypes: ['omnivore'],
    excludesAllergies: ['dairy', 'nuts', 'eggs'],
  },
  {
    id: 'd2',
    name: 'Mediterranean Chickpea Bowl',
    slot: 'dinner',
    ingredients: ['chickpeas', 'cucumber', 'feta', 'olive oil'],
    macros: { calories: 490, protein: 18, carbs: 52, fat: 22 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean'],
    excludesAllergies: ['gluten', 'nuts', 'eggs'],
  },
  {
    id: 'd3',
    name: 'Zucchini Noodles & Pesto',
    slot: 'dinner',
    ingredients: ['zucchini', 'basil pesto', 'cherry tomatoes'],
    macros: { calories: 380, protein: 12, carbs: 24, fat: 28 },
    dietTypes: ['vegetarian', 'keto', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'eggs'],
  },
  {
    id: 'd4',
    name: 'Beef & Sweet Potato',
    slot: 'dinner',
    ingredients: ['lean beef', 'sweet potato', 'green beans'],
    macros: { calories: 620, protein: 44, carbs: 48, fat: 26 },
    dietTypes: ['omnivore', 'keto'],
    excludesAllergies: ['gluten', 'dairy', 'nuts', 'eggs'],
  },
  {
    id: 'd5',
    name: 'Baked Salmon with Vegetables',
    slot: 'dinner',
    ingredients: ['salmon fillet', 'broccoli', 'cherry tomatoes', 'olive oil', 'lemon', 'garlic'],
    macros: { calories: 520, protein: 42, carbs: 18, fat: 32 },
    dietTypes: ['omnivore', 'mediterranean', 'keto'],
    excludesAllergies: ['gluten', 'dairy', 'nuts', 'eggs'],
    cookingSteps: [
      'Preheat oven to 200°C.',
      'Place salmon on a baking tray, season with salt, pepper, and minced garlic.',
      'Arrange broccoli and cherry tomatoes around the salmon.',
      'Drizzle everything with olive oil and lemon juice.',
      'Bake for 18-20 minutes until salmon flakes easily with a fork.',
    ],
    cookTime: 30,
    difficulty: 'Easy',
  },
  {
    id: 'd6',
    name: 'Moussaka',
    slot: 'dinner',
    ingredients: ['minced beef', 'eggplant', 'tomatoes', 'onion', 'cinnamon', 'olive oil', 'milk', 'flour'],
    macros: { calories: 580, protein: 32, carbs: 38, fat: 32 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['nuts', 'eggs'],
    cookingSteps: [
      'Slice eggplant, salt it, and let sit for 20 minutes. Pat dry and grill until soft.',
      'Brown minced beef with onion, add crushed tomatoes, cinnamon, salt, and pepper. Simmer 15 minutes.',
      'Make a simple béchamel: melt butter, whisk in flour, gradually add warm milk, stir until thick.',
      'Layer eggplant, meat sauce, and béchamel in a baking dish.',
      'Bake at 180°C for 40 minutes until golden on top. Rest 10 minutes before serving.',
    ],
    cookTime: 90,
    difficulty: 'Hard',
  },
  {
    id: 'd7',
    name: 'Shrimp Pasta',
    slot: 'dinner',
    ingredients: ['shrimp', 'pasta', 'garlic', 'cherry tomatoes', 'olive oil', 'parsley', 'lemon'],
    macros: { calories: 540, protein: 36, carbs: 58, fat: 16 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'nuts', 'eggs'],
    cookingSteps: [
      'Cook pasta in salted boiling water until al dente. Reserve half a cup of pasta water.',
      'Sauté minced garlic in olive oil for 1 minute until fragrant.',
      'Add shrimp and cook 2 minutes per side until pink.',
      'Add cherry tomatoes and cook 3 more minutes.',
      'Toss in drained pasta with a splash of pasta water. Finish with parsley and lemon juice.',
    ],
    cookTime: 25,
    difficulty: 'Easy',
  },
  {
    id: 'd8',
    name: 'Stuffed Peppers',
    slot: 'dinner',
    ingredients: ['bell peppers', 'brown rice', 'minced turkey', 'tomatoes', 'onion', 'feta cheese'],
    macros: { calories: 490, protein: 34, carbs: 46, fat: 18 },
    dietTypes: ['omnivore', 'mediterranean'],
    excludesAllergies: ['gluten', 'nuts', 'eggs'],
    cookingSteps: [
      'Cook brown rice until tender. Preheat oven to 180°C.',
      'Brown turkey mince with onion and crushed tomatoes. Season well.',
      'Mix turkey with cooked rice and crumbled feta.',
      'Cut tops off peppers, remove seeds, and fill with the mixture.',
      'Place in a baking dish with a little water, cover with foil, bake 35 minutes.',
    ],
    cookTime: 60,
    difficulty: 'Medium',
  },
  {
    id: 's1',
    name: 'Apple & Almond Butter',
    slot: 'snack',
    ingredients: ['apple', 'almond butter'],
    macros: { calories: 220, protein: 6, carbs: 28, fat: 12 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'eggs'],
  },
  {
    id: 's2',
    name: 'Protein Shake',
    slot: 'snack',
    ingredients: ['whey protein', 'banana', 'milk'],
    macros: { calories: 280, protein: 32, carbs: 30, fat: 4 },
    dietTypes: ['omnivore'],
    excludesAllergies: ['gluten', 'nuts', 'eggs'],
  },
  {
    id: 's3',
    name: 'Hummus & Carrots',
    slot: 'snack',
    ingredients: ['hummus', 'carrot sticks'],
    macros: { calories: 180, protein: 6, carbs: 22, fat: 8 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean', 'keto'],
    excludesAllergies: ['gluten', 'dairy', 'eggs', 'nuts'],
  },
  {
    id: 's4',
    name: 'Cheese & Crackers',
    slot: 'snack',
    ingredients: ['cheddar', 'crackers'],
    macros: { calories: 240, protein: 10, carbs: 18, fat: 14 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean'],
    excludesAllergies: ['nuts', 'eggs', 'gluten'],
  },
  {
    id: 's5',
    name: 'Greek Yogurt with Honey',
    slot: 'snack',
    ingredients: ['Greek yogurt', 'honey', 'walnuts', 'cinnamon'],
    macros: { calories: 200, protein: 14, carbs: 22, fat: 8 },
    dietTypes: ['omnivore', 'vegetarian', 'mediterranean'],
    excludesAllergies: ['gluten', 'eggs'],
    cookingSteps: [
      'Spoon Greek yogurt into a bowl.',
      'Drizzle honey over the top.',
      'Sprinkle crushed walnuts and a pinch of cinnamon.',
      'Serve immediately.',
    ],
    cookTime: 3,
    difficulty: 'Easy',
  },
  {
    id: 's6',
    name: 'Rice Cakes with Peanut Butter',
    slot: 'snack',
    ingredients: ['rice cakes', 'peanut butter', 'banana', 'chia seeds'],
    macros: { calories: 250, protein: 8, carbs: 34, fat: 10 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan'],
    excludesAllergies: ['gluten', 'dairy', 'eggs'],
    cookingSteps: [
      'Place rice cakes on a plate.',
      'Spread peanut butter evenly over each rice cake.',
      'Slice banana and arrange on top.',
      'Sprinkle chia seeds over everything.',
    ],
    cookTime: 3,
    difficulty: 'Easy',
  },
  {
    id: 's7',
    name: 'Mixed Nuts & Dried Fruit',
    slot: 'snack',
    ingredients: ['almonds', 'walnuts', 'dried cranberries', 'dark chocolate chips'],
    macros: { calories: 260, protein: 7, carbs: 24, fat: 16 },
    dietTypes: ['omnivore', 'vegetarian', 'vegan', 'mediterranean'],
    excludesAllergies: ['gluten', 'dairy', 'eggs'],
    cookingSteps: [
      'Measure out portions of almonds, walnuts, cranberries, and chocolate chips.',
      'Mix together in a small bowl.',
      'Serve immediately or store in an airtight container.',
    ],
    cookTime: 2,
    difficulty: 'Easy',
  },
];

export function filterTemplates(
  dietType: DietType,
  allergies: string[]
): Meal[] {
  const activeAllergies = (allergies ?? []).filter((a) => a !== 'none');

  return MEAL_TEMPLATES.filter((meal) => {
    if (!meal.dietTypes.includes(dietType)) return false;
    if (activeAllergies.length === 0) return true;
    return !activeAllergies.some((allergy) =>
      meal.excludesAllergies.includes(allergy as Allergy)
    );
  });
}

export function pickMealForSlot(
  pool: Meal[],
  slot: MealSlot,
  excludeIds: string[] = []
): Meal | null {
  const candidates = pool.filter(
    (m) => m.slot === slot && !excludeIds.includes(m.id)
  );
  if (candidates.length === 0) return null;
  return candidates[Math.floor(Math.random() * candidates.length)];
}
